#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

for ((r = 1; r <= 100; r++)); do
	if [ $((r % 3)) -eq 0 ] && [ $((r % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((r % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((r % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$r"
	fi
done
