#!/usr/bin/env bash
# Bash script that displays the time and hours

counter=0
while [ $counter -le 12 ]
do
	echo "Hour: $counter"
	count=1
	while [ $count -le 59 ]
	do
		echo "$count"
		((count++))
	done
	((counter++))
done
